package jobs

import (
	"context"
	"encoding/json"
	"maps"
	"strings"
	"testing"

	"github.com/kombifyio/techstack/internal/portinventory"
	"github.com/kombifyio/techstack/internal/stackkitrelease"
	"github.com/kombifyio/techstack/pkg/api/agentpb"
)

// Generated by the pinned StackKits workloadremoval public contract. This is
// genuine transport evidence, not a Techstack reconstruction of its digest.
const localRemovalEvidenceFixture = `{"apiVersion":"stackkit.workload-removal-evidence/v2","authority":{"appliedRequestDigest":"sha256:1d85f2856fa97b4b01311f213e61e39915e1abcfa78110ef8373e21be433503a","artifactDigest":"sha256:7f732b4114fdf5311ee9b70367d1c3c846b86d23cbc2d800a7c5ec460ba8b8ab","authorization":{"keyId":"owner-key","ownerRef":"owner/local","value":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},"dataDisposition":"retain","executionChannelRef":"channel-main","instanceRef":"immich-server-node-main","nodeRef":"main","planHash":"sha256:64879f7d6b960a01909762d911a32d4582c20010c5641ee90278b644a9e3b525","requestDigest":"sha256:b010cc2e8a717a949cd18f49de470a77bad8b49e4013909c426d6862fcf359b8","requestedAt":"2026-08-22T10:00:00Z","requirementId":"runtime-photos","runtimeOwnerRef":"coolify","siteRef":"home","validUntil":"2026-08-22T10:01:00Z","workloadRef":"photos"},"evidenceDigest":"sha256:3d0bbec39e96e553a44a18c0c1d430551b05c80b2c32bb1fd00da135744f3646","result":{"apiVersion":"stackkit.workload-removal-result/v2","outcome":{"artifactDigest":"sha256:7f732b4114fdf5311ee9b70367d1c3c846b86d23cbc2d800a7c5ec460ba8b8ab","dataDisposition":"retain","instanceRef":"immich-server-node-main","observationDigest":"sha256:5ad38304b535c2987dbd24657c1a11b884984ff600d9f389deb0d4e634fee792","observationRef":"removal-observation://selected-paas/photos","observedState":"absent","requirementId":"runtime-photos","runtimeOwnerRef":"coolify","status":"removed","workloadRef":"photos"},"removedAt":"2026-08-22T10:00:01Z","requestDigest":"sha256:b010cc2e8a717a949cd18f49de470a77bad8b49e4013909c426d6862fcf359b8","resultDigest":"sha256:104ad13e0077f80f9378f7177b7fa49616770b2e87fa6724c1a8125211bbf443"}}`

type localRemovalSender struct {
	evidence       []byte
	evidenceByNode map[string][]byte
	agentIDs       []string
	commands       []*agentpb.StackKitCommand
}

func (sender *localRemovalSender) SendStackKitCommand(_ context.Context, agentID string, command *agentpb.StackKitCommand) (*agentpb.StackKitResult, error) {
	sender.agentIDs = append(sender.agentIDs, agentID)
	sender.commands = append(sender.commands, command)
	evidence := sender.evidence
	if sender.evidenceByNode != nil {
		evidence = sender.evidenceByNode[command.LocalNodeRef]
	}
	envelope, _ := json.Marshal(map[string]any{
		"schemaVersion": "stackkit.command-result/v1", "command": "stackkit remove", "status": "success",
		"data": map[string]any{"output": string(evidence)},
	})
	return &agentpb.StackKitResult{Success: true, CommandResultJson: envelope}, nil
}

func TestLocalStackKitTeardownBindsTerminalEvidenceToThePortPlan(t *testing.T) {
	planHash := "sha256:64879f7d6b960a01909762d911a32d4582c20010c5641ee90278b644a9e3b525"
	authority := LocalStackKitTeardownAuthority{
		SchemaVersion: localStackKitTeardownAuthorityVersion,
		TechstackID:   "stack-local", StackKitInstanceID: "kit-local", TenantID: "tenant-local", OwnerID: "owner-local",
		StackKit: "basement-kit", PlanHash: planHash,
		AppliedRequestDigest: "sha256:1d85f2856fa97b4b01311f213e61e39915e1abcfa78110ef8373e21be433503a",
		Servers: []LocalStackKitTeardownServerAuthority{{ServerID: "server-local", AgentID: "agent-local", Workloads: []LocalStackKitTeardownWorkloadAuthority{{
			WorkloadRef: "photos", RequirementID: "runtime-photos", InstanceRef: "immich-server-node-main", RuntimeOwnerRef: "coolify",
			SiteRef: "home", NodeRef: "main", ExecutionChannelRef: "channel-main",
			ArtifactDigests: []string{"sha256:7f732b4114fdf5311ee9b70367d1c3c846b86d23cbc2d800a7c5ec460ba8b8ab"},
		}}}},
	}
	snapshot := testPortTeardownSnapshotForPlan("tenant-local", "owner-local", "stack-local", planHash)
	job := &Job{
		ID: "destroy-local", Type: JobTypeDestroy, TargetID: "stack-local",
		Payload: map[string]interface{}{"tenant_id": "tenant-local", "owner_id": "owner-local", ManagedRuntimeDecommissionRequiredField: false},
		Result:  map[string]interface{}{LocalStackKitTeardownAuthorityResultField: authority},
	}
	sender := &localRemovalSender{evidence: []byte(localRemovalEvidenceFixture)}
	if err := removeLocalStackKitWorkloadsWithRelease(t.Context(), &ProvisionConfig{StackKitCommander: sender}, job, snapshot, stackkitrelease.Release{}); err != nil {
		t.Fatalf("removeLocalStackKitWorkloadsWithRelease: %v", err)
	}
	if len(sender.commands) != 1 || len(sender.agentIDs) != 1 || sender.agentIDs[0] != "agent-local" || sender.commands[0].Operation != agentpb.StackKitOperation_STACKKIT_OPERATION_REMOVE ||
		sender.commands[0].StackkitInstanceId != "kit-local" || sender.commands[0].WorkloadRef != "photos" || !sender.commands[0].OwnerApproved ||
		sender.commands[0].LocalNodeRef != "main" || sender.commands[0].LocalExecutionChannelRef != "channel-main" {
		t.Fatalf("typed local removal command = %#v", sender.commands)
	}
	stored, ok := job.Result[LocalStackKitRemovalEvidenceResultField].([]interface{})
	if !ok || len(stored) != 1 {
		t.Fatalf("durable local removal evidence = %#v", job.Result[LocalStackKitRemovalEvidenceResultField])
	}
	if err := removeLocalStackKitWorkloadsWithRelease(t.Context(), &ProvisionConfig{StackKitCommander: sender}, job, snapshot, stackkitrelease.Release{}); err != nil || len(sender.commands) != 1 {
		t.Fatalf("replay redrove a completed removal: error=%v commands=%d", err, len(sender.commands))
	}
	job.Result[LocalStackKitRemovalEvidenceResultField] = []interface{}{}
	missingSender := &localRemovalSender{evidence: []byte(localRemovalEvidenceFixture)}
	if err := removeLocalStackKitWorkloadsWithRelease(t.Context(), &ProvisionConfig{StackKitCommander: missingSender}, job, snapshot, stackkitrelease.Release{}); err == nil || len(missingSender.commands) != 0 {
		t.Fatalf("incomplete durable evidence was redriven: error=%v commands=%d", err, len(missingSender.commands))
	}
	foreignSnapshot := snapshot
	foreignSnapshot.Generations = append([]portinventory.TeardownGeneration(nil), snapshot.Generations...)
	foreignSnapshot.Generations[0].ServerID = "server-foreign"
	foreignJob := &Job{
		ID: "destroy-foreign", Type: JobTypeDestroy, TargetID: "stack-local",
		Payload: map[string]interface{}{"tenant_id": "tenant-local", "owner_id": "owner-local"},
		Result:  map[string]interface{}{LocalStackKitTeardownAuthorityResultField: authority},
	}
	foreignSender := &localRemovalSender{evidence: []byte(localRemovalEvidenceFixture)}
	if err := removeLocalStackKitWorkloadsWithRelease(t.Context(), &ProvisionConfig{StackKitCommander: foreignSender}, foreignJob, foreignSnapshot, stackkitrelease.Release{}); err == nil || len(foreignSender.commands) != 0 {
		t.Fatalf("foreign server generation reached removal: error=%v commands=%d", err, len(foreignSender.commands))
	}
}

func TestLocalStackKitTeardownPartitionsThreeServersByApprovedAgent(t *testing.T) {
	planHash := "sha256:" + strings.Repeat("a", 64)
	snapshot := testPortTeardownSnapshotForNodes("tenant-local", "owner-local", "stack-local", planHash, map[string]string{
		"server-a": "node-a", "server-b": "node-b", "server-c": "node-c",
	})
	placements := []interface{}{
		map[string]interface{}{"siteRef": "home-a", "nodeRef": "node-a", "executionChannelRef": "channel-a"},
		map[string]interface{}{"siteRef": "home-b", "nodeRef": "node-b", "executionChannelRef": "channel-b"},
		map[string]interface{}{"siteRef": "home-c", "nodeRef": "node-c", "executionChannelRef": "channel-c"},
	}
	runtimeSummary := map[string]any{
		metadataKeyStackKitCatalogRef: "basement-kit",
		metadataKeyStackKitOutputs: map[string]interface{}{"apply": map[string]interface{}{
			"planHash": planHash, "appliedRequestDigest": "sha256:" + strings.Repeat("b", 64),
			"appliedWorkloads": []interface{}{map[string]interface{}{
				"workloadRef": "photos", "requirementId": "runtime-photos", "instanceRef": "photos-cluster", "runtimeOwnerRef": "docker",
				"placements": placements, "artifacts": []interface{}{map[string]interface{}{"digest": "sha256:" + strings.Repeat("d", 64)}},
			}},
		}},
	}
	bindings := []LocalStackKitTeardownNodeBinding{
		{NodeRef: "node-c", ServerID: "server-c", AgentID: "agent-c"},
		{NodeRef: "node-a", ServerID: "server-a", AgentID: "agent-a"},
		{NodeRef: "node-b", ServerID: "server-b", AgentID: "agent-b"},
	}
	authority, err := BuildLocalStackKitTeardownAuthority("stack-local", "kit-local", "tenant-local", "owner-local", runtimeSummary, snapshot, bindings)
	if err != nil || len(authority.Servers) != 3 || authority.Servers[0].AgentID != "agent-a" || authority.Servers[1].AgentID != "agent-b" || authority.Servers[2].AgentID != "agent-c" {
		t.Fatalf("three-server authority = %#v, error = %v", authority, err)
	}
	job := &Job{TargetID: "stack-local", Payload: map[string]interface{}{"tenant_id": "tenant-local", "owner_id": "owner-local"}, Result: map[string]interface{}{LocalStackKitTeardownAuthorityResultField: authority}}
	if _, err := boundLocalStackKitTeardownAuthority(job, snapshot); err != nil {
		t.Fatalf("boundLocalStackKitTeardownAuthority() error = %v", err)
	}
	incomplete := authority
	incomplete.Servers = append([]LocalStackKitTeardownServerAuthority(nil), authority.Servers[:2]...)
	job.Result[LocalStackKitTeardownAuthorityResultField] = incomplete
	if _, err := boundLocalStackKitTeardownAuthority(job, snapshot); err == nil {
		t.Fatal("two-server authority was accepted for a three-server snapshot")
	}
}

func TestLocalStackKitTeardownRequiresExactEvidenceFromAllThreeAgents(t *testing.T) {
	// Provider-control boundary: one server's terminal observation must never
	// authorize release of another server's host-port claims.
	authority, snapshot, evidenceByNode := threeServerLocalRemovalFixture(t)
	newJob := func() *Job {
		return &Job{ID: "destroy-three", Type: JobTypeDestroy, TargetID: authority.TechstackID,
			Payload: map[string]interface{}{"tenant_id": authority.TenantID, "owner_id": authority.OwnerID},
			Result:  map[string]interface{}{LocalStackKitTeardownAuthorityResultField: authority}}
	}
	sender := &localRemovalSender{evidenceByNode: evidenceByNode}
	job := newJob()
	if err := removeLocalStackKitWorkloadsWithRelease(t.Context(), &ProvisionConfig{StackKitCommander: sender}, job, snapshot, stackkitrelease.Release{}); err != nil {
		t.Fatal(err)
	}
	if strings.Join(sender.agentIDs, ",") != "agent-a,agent-b,agent-c" || len(sender.commands) != 3 {
		t.Fatalf("three-server dispatch agents=%v commands=%d", sender.agentIDs, len(sender.commands))
	}
	if err := removeLocalStackKitWorkloadsWithRelease(t.Context(), &ProvisionConfig{StackKitCommander: sender}, job, snapshot, stackkitrelease.Release{}); err != nil || len(sender.commands) != 3 {
		t.Fatalf("three-server replay redrove removal: error=%v commands=%d", err, len(sender.commands))
	}
	foreign := maps.Clone(evidenceByNode)
	foreign["node-b"] = foreign["node-a"]
	foreignJob := newJob()
	foreignSender := &localRemovalSender{evidenceByNode: foreign}
	if err := removeLocalStackKitWorkloadsWithRelease(t.Context(), &ProvisionConfig{StackKitCommander: foreignSender}, foreignJob, snapshot, stackkitrelease.Release{}); err == nil || foreignJob.Result[LocalStackKitRemovalEvidenceResultField] != nil {
		t.Fatalf("one agent satisfied another placement: error=%v result=%#v", err, foreignJob.Result)
	}
}

func threeServerLocalRemovalFixture(t *testing.T) (LocalStackKitTeardownAuthority, portinventory.TeardownSnapshot, map[string][]byte) {
	t.Helper()
	const appliedDigest = "sha256:02d47a25c822b8e239cd6ba8c35ac4ca93bb9a4a4d0d45c55ee63c1925ef48e4"
	const planHash = "sha256:64879f7d6b960a01909762d911a32d4582c20010c5641ee90278b644a9e3b525"
	const artifactDigest = "sha256:9a05b621edd6ef92a55ab68b340d0d67ccdc3a2938cd28e9a3603a1e6af6e779"
	authority := LocalStackKitTeardownAuthority{
		SchemaVersion: localStackKitTeardownAuthorityVersion, TechstackID: "stack-three", StackKitInstanceID: "kit-three",
		TenantID: "tenant-three", OwnerID: "owner-three", StackKit: "basement-kit", PlanHash: planHash, AppliedRequestDigest: appliedDigest,
	}
	for index, nodeRef := range []string{"node-a", "node-b", "node-c"} {
		suffix := string(rune('a' + index))
		authority.Servers = append(authority.Servers, LocalStackKitTeardownServerAuthority{ServerID: "server-" + suffix, AgentID: "agent-" + suffix, Workloads: []LocalStackKitTeardownWorkloadAuthority{{WorkloadRef: "photos", RequirementID: "runtime-photos", InstanceRef: "photos-cluster", RuntimeOwnerRef: "stackkits-photos-runtime", SiteRef: "home-" + suffix, NodeRef: nodeRef, ExecutionChannelRef: "channel-" + suffix, ArtifactDigests: []string{artifactDigest}}}})
	}
	snapshot := testPortTeardownSnapshotForNodes(authority.TenantID, authority.OwnerID, authority.TechstackID, authority.PlanHash, map[string]string{"server-a": "node-a", "server-b": "node-b", "server-c": "node-c"})
	return authority, snapshot, map[string][]byte{
		"node-a": []byte(threeServerRemovalEvidenceNodeA),
		"node-b": []byte(threeServerRemovalEvidenceNodeB),
		"node-c": []byte(threeServerRemovalEvidenceNodeC),
	}
}

// Generated once by StackKits v0.21.13 SealRequestForPlacement/NewEvidence.
// Techstack consumes the public parser only; it does not reconstruct evidence.
const threeServerRemovalEvidenceNodeA = `{"apiVersion":"stackkit.workload-removal-evidence/v2","authority":{"appliedRequestDigest":"sha256:02d47a25c822b8e239cd6ba8c35ac4ca93bb9a4a4d0d45c55ee63c1925ef48e4","artifactDigest":"sha256:9a05b621edd6ef92a55ab68b340d0d67ccdc3a2938cd28e9a3603a1e6af6e779","authorization":{"keyId":"owner-key","ownerRef":"owner/local","value":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},"dataDisposition":"retain","executionChannelRef":"channel-a","instanceRef":"photos-cluster","nodeRef":"node-a","planHash":"sha256:64879f7d6b960a01909762d911a32d4582c20010c5641ee90278b644a9e3b525","requestDigest":"sha256:3ed8b3d702e9651681c6b7557551f34cdae38eb473cecb488d8ca34615a0caf3","requestedAt":"2026-08-22T12:00:00Z","requirementId":"runtime-photos","runtimeOwnerRef":"stackkits-photos-runtime","siteRef":"home-a","validUntil":"2026-08-22T12:01:00Z","workloadRef":"photos"},"evidenceDigest":"sha256:28fe0602152d59b90dd6f6e45a48e7dfce3e493a2a06c0a77bc036b4e6eca73f","result":{"apiVersion":"stackkit.workload-removal-result/v2","outcome":{"artifactDigest":"sha256:9a05b621edd6ef92a55ab68b340d0d67ccdc3a2938cd28e9a3603a1e6af6e779","dataDisposition":"retain","instanceRef":"photos-cluster","observationDigest":"sha256:8ef0634e1926bda49f9beeb808769d253d2016a9553a6932851243d0f6a90f12","observationRef":"removal-observation://docker/photos/node-a","observedState":"absent","requirementId":"runtime-photos","runtimeOwnerRef":"stackkits-photos-runtime","status":"removed","workloadRef":"photos"},"removedAt":"2026-08-22T12:00:01Z","requestDigest":"sha256:3ed8b3d702e9651681c6b7557551f34cdae38eb473cecb488d8ca34615a0caf3","resultDigest":"sha256:0b35ddb88225eb40687a0608c0f4f4735fdaa7cdb66603a54444fe3216a3595c"}}`
const threeServerRemovalEvidenceNodeB = `{"apiVersion":"stackkit.workload-removal-evidence/v2","authority":{"appliedRequestDigest":"sha256:02d47a25c822b8e239cd6ba8c35ac4ca93bb9a4a4d0d45c55ee63c1925ef48e4","artifactDigest":"sha256:9a05b621edd6ef92a55ab68b340d0d67ccdc3a2938cd28e9a3603a1e6af6e779","authorization":{"keyId":"owner-key","ownerRef":"owner/local","value":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},"dataDisposition":"retain","executionChannelRef":"channel-b","instanceRef":"photos-cluster","nodeRef":"node-b","planHash":"sha256:64879f7d6b960a01909762d911a32d4582c20010c5641ee90278b644a9e3b525","requestDigest":"sha256:e96dfb9a2d321954104ad41f27d415a076f3d059567865d0832d537bce427e41","requestedAt":"2026-08-22T12:00:00Z","requirementId":"runtime-photos","runtimeOwnerRef":"stackkits-photos-runtime","siteRef":"home-b","validUntil":"2026-08-22T12:01:00Z","workloadRef":"photos"},"evidenceDigest":"sha256:9938ec878368e25225e7ac25cfbdb8d99d80220789dfae3a7fea3b0b74db22d1","result":{"apiVersion":"stackkit.workload-removal-result/v2","outcome":{"artifactDigest":"sha256:9a05b621edd6ef92a55ab68b340d0d67ccdc3a2938cd28e9a3603a1e6af6e779","dataDisposition":"retain","instanceRef":"photos-cluster","observationDigest":"sha256:53cc1357b13c4858fef3a005b86a4d8f8f27fd4a5a8b4ff6c666cc31a113ff1c","observationRef":"removal-observation://docker/photos/node-b","observedState":"absent","requirementId":"runtime-photos","runtimeOwnerRef":"stackkits-photos-runtime","status":"removed","workloadRef":"photos"},"removedAt":"2026-08-22T12:00:01Z","requestDigest":"sha256:e96dfb9a2d321954104ad41f27d415a076f3d059567865d0832d537bce427e41","resultDigest":"sha256:37695e96c1efc6f6acb9e1eee1d8f7b5950bc559eaee4e109947e554e737710d"}}`
const threeServerRemovalEvidenceNodeC = `{"apiVersion":"stackkit.workload-removal-evidence/v2","authority":{"appliedRequestDigest":"sha256:02d47a25c822b8e239cd6ba8c35ac4ca93bb9a4a4d0d45c55ee63c1925ef48e4","artifactDigest":"sha256:9a05b621edd6ef92a55ab68b340d0d67ccdc3a2938cd28e9a3603a1e6af6e779","authorization":{"keyId":"owner-key","ownerRef":"owner/local","value":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},"dataDisposition":"retain","executionChannelRef":"channel-c","instanceRef":"photos-cluster","nodeRef":"node-c","planHash":"sha256:64879f7d6b960a01909762d911a32d4582c20010c5641ee90278b644a9e3b525","requestDigest":"sha256:c48f68a84222f84ea908bd5ab1187510cec64628862b79e5a153faecc323da6d","requestedAt":"2026-08-22T12:00:00Z","requirementId":"runtime-photos","runtimeOwnerRef":"stackkits-photos-runtime","siteRef":"home-c","validUntil":"2026-08-22T12:01:00Z","workloadRef":"photos"},"evidenceDigest":"sha256:562ae7005f723261d80a97073e2d91b903a807c13b0cde9b49e2775b0e0d3dc4","result":{"apiVersion":"stackkit.workload-removal-result/v2","outcome":{"artifactDigest":"sha256:9a05b621edd6ef92a55ab68b340d0d67ccdc3a2938cd28e9a3603a1e6af6e779","dataDisposition":"retain","instanceRef":"photos-cluster","observationDigest":"sha256:3f6e2dc2063ab68e9610c3d88cc0fde1e43713323b2304a81c251903ac6f12d6","observationRef":"removal-observation://docker/photos/node-c","observedState":"absent","requirementId":"runtime-photos","runtimeOwnerRef":"stackkits-photos-runtime","status":"removed","workloadRef":"photos"},"removedAt":"2026-08-22T12:00:01Z","requestDigest":"sha256:c48f68a84222f84ea908bd5ab1187510cec64628862b79e5a153faecc323da6d","resultDigest":"sha256:5d057a60fab1f976e44aae6e3cab1f6c399a47b1dba0ad1033a90461a0d6e579"}}`
