package walletsync

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"

	tsauth "github.com/kombifyio/techstack/pkg/auth"
	"github.com/kombifyio/techstack/pkg/controlplane"
	"github.com/pocketbase/dbx"
	"github.com/pocketbase/pocketbase/core"
)

const (
	ownerWalletServiceID        = "pocketid:owner"
	loginGatewayWalletServiceID = "stackkit:login-gateway"
	recoveryWalletServiceID     = "stackkit:recovery"
)

type App interface {
	FindCollectionByNameOrId(nameOrId string) (*core.Collection, error)
	FindRecordsByFilter(collectionModelOrIdentifier any, filter string, sort string, limit int, offset int, params ...dbx.Params) ([]*core.Record, error)
	Save(model core.Model) error
}

type SyncRequest struct {
	TenantID  string
	OwnerID   string
	StackID   string
	StackName string
	Result    map[string]interface{}
}

type WalletItem struct {
	ServiceID     string
	SourceRef     string
	Name          string
	Kind          string
	Username      string
	Secret        string
	URL           string
	Notes         string
	ItemClass     string
	SourceType    string
	AccessMode    string
	Revealable    bool
	AutoGenerated bool
}

func SyncStackKitOutputs(app App, req SyncRequest) (int, error) {
	if app == nil || strings.TrimSpace(req.OwnerID) == "" || strings.TrimSpace(req.StackID) == "" || req.Result == nil {
		return 0, nil
	}

	items := WalletItemsFromResult(req)
	if len(items) == 0 {
		return 0, nil
	}

	collection, err := app.FindCollectionByNameOrId("wallet")
	if err != nil {
		return 0, fmt.Errorf("wallet collection missing: %w", err)
	}

	upserted := 0
	for _, item := range items {
		if strings.TrimSpace(item.ServiceID) == "" || strings.TrimSpace(item.SourceRef) == "" {
			continue
		}
		if err := upsertWalletItem(app, collection, req, item); err != nil {
			return upserted, err
		}
		upserted++
	}
	return upserted, nil
}

func SyncStackKitOutputsToStore(ctx context.Context, store controlplane.WalletStore, req SyncRequest) (int, error) {
	tenantID := firstNonEmpty(req.TenantID, req.OwnerID)
	if store == nil || strings.TrimSpace(tenantID) == "" || strings.TrimSpace(req.OwnerID) == "" || strings.TrimSpace(req.StackID) == "" || req.Result == nil {
		return 0, nil
	}

	items := WalletItemsFromResult(req)
	if len(items) == 0 {
		return 0, nil
	}

	upserted := 0
	for _, item := range items {
		if strings.TrimSpace(item.ServiceID) == "" || strings.TrimSpace(item.SourceRef) == "" {
			continue
		}
		if err := upsertWalletStoreItem(ctx, store, tenantID, req, item); err != nil {
			return upserted, err
		}
		upserted++
	}
	return upserted, nil
}

//nolint:goconst // Output keys intentionally accept multiple StackKits wire aliases.
func WalletItemsFromResult(req SyncRequest) []WalletItem {
	outputs, ok := stackKitOutputs(req.Result)
	if !ok {
		return nil
	}

	items := []WalletItem{}
	owner := firstNestedMap(outputs, []string{"identity", "owner"}, []string{"admin_bootstrap", "owner"}, []string{"owner"})
	if len(owner) > 0 {
		items = append(items, ownerWalletItem(req, owner))
	}

	loginGateway := firstNestedMap(outputs,
		[]string{"identity", "login_gateway"},
		[]string{"identity", "loginGateway"},
		[]string{"login_gateway"},
		[]string{"loginGateway"},
		[]string{"launch"},
	)
	if len(loginGateway) > 0 && firstOutputString(loginGateway, "url", "launch_url", "manage_url", "admin_url") != "" {
		items = append(items, loginGatewayWalletItem(req, loginGateway))
	}

	recovery := firstNestedMap(outputs, []string{"identity", "recovery"}, []string{"admin_bootstrap", "recovery"}, []string{"recovery"})
	if len(recovery) > 0 {
		if secret := recoverySecretRef(recovery); secret != "" || firstOutputString(recovery, "url", "recovery_url") != "" {
			items = append(items, recoveryWalletItem(req, recovery, secret))
		}
	}

	return items
}

func stackKitOutputs(result map[string]interface{}) (map[string]interface{}, bool) {
	for _, key := range []string{"stackkit_outputs", "stackkitOutputs", "stackkit_identity_outputs", "identity_outputs"} {
		if out, ok := mapFromAny(result[key]); ok {
			return out, true
		}
	}
	if data, ok := mapFromAny(result["data"]); ok {
		return stackKitOutputs(data)
	}
	if _, ok := result["identity"]; ok {
		return result, true
	}
	if _, ok := result["login_gateway"]; ok {
		return result, true
	}
	if _, ok := result["recovery"]; ok {
		return result, true
	}
	return nil, false
}

func ownerWalletItem(req SyncRequest, owner map[string]interface{}) WalletItem {
	username := firstOutputString(owner, "email", "username")
	display := firstOutputString(owner, "displayName", "display_name", "name", "username", "email")
	return WalletItem{
		ServiceID:     firstOutputString(owner, "service_id", "serviceId", ownerWalletServiceID),
		SourceRef:     firstOutputString(owner, "source_ref", "sourceRef", "pocketid:"+req.StackID+":owner"),
		Name:          firstOutputString(owner, "name", "display_name", "Pocket ID Owner"),
		Kind:          "other",
		Username:      username,
		URL:           firstOutputString(owner, "manage_url", "admin_url", "url", "launch_url"),
		Notes:         fmt.Sprintf("StackKit owner access for %s (%s).", displayStackName(req), display),
		ItemClass:     "user_account",
		SourceType:    "pocketid",
		AccessMode:    "manage",
		Revealable:    false,
		AutoGenerated: true,
	}
}

func loginGatewayWalletItem(req SyncRequest, gateway map[string]interface{}) WalletItem {
	return WalletItem{
		ServiceID:     firstOutputString(gateway, "service_id", "serviceId", loginGatewayWalletServiceID),
		SourceRef:     firstOutputString(gateway, "source_ref", "sourceRef", "stackkit:"+req.StackID+":login-gateway"),
		Name:          firstOutputString(gateway, "name", "display_name", "displayName", "Login Gateway"),
		Kind:          "other",
		URL:           firstOutputString(gateway, "url", "launch_url", "manage_url", "admin_url"),
		Notes:         "StackKit login gateway launch entry for " + displayStackName(req) + ".",
		ItemClass:     "launch",
		SourceType:    "stackkit",
		AccessMode:    "open",
		Revealable:    false,
		AutoGenerated: true,
	}
}

func recoveryWalletItem(req SyncRequest, recovery map[string]interface{}, secret string) WalletItem {
	return WalletItem{
		ServiceID:     firstOutputString(recovery, "service_id", "serviceId", recoveryWalletServiceID),
		SourceRef:     firstOutputString(recovery, "source_ref", "sourceRef", "stackkit:"+req.StackID+":recovery"),
		Name:          firstOutputString(recovery, "name", "display_name", "displayName", "Stack recovery bundle"),
		Kind:          "other",
		Username:      firstOutputString(recovery, "username", "email"),
		Secret:        secret,
		URL:           firstOutputString(recovery, "url", "recovery_url"),
		Notes:         "StackKit recovery reference for " + displayStackName(req) + ".",
		ItemClass:     "recovery",
		SourceType:    "stackkit",
		AccessMode:    "reveal",
		Revealable:    strings.TrimSpace(secret) != "",
		AutoGenerated: true,
	}
}

func upsertWalletItem(app App, collection *core.Collection, req SyncRequest, item WalletItem) error {
	existing, err := findExistingWalletItem(app, collection, req, item)
	if err != nil {
		return err
	}
	record := existing
	if record == nil {
		record = core.NewRecord(collection)
	}

	fields := map[string]any{
		"owner_id":       req.OwnerID,
		"stack_id":       req.StackID,
		"service_id":     item.ServiceID,
		"source_ref":     item.SourceRef,
		"name":           item.Name,
		"kind":           firstNonEmpty(item.Kind, "other"),
		"username":       item.Username,
		"url":            item.URL,
		"notes":          item.Notes,
		"item_class":     item.ItemClass,
		"source_type":    item.SourceType,
		"access_mode":    item.AccessMode,
		"revealable":     item.Revealable,
		"auto_generated": item.AutoGenerated,
	}
	if item.Secret != "" {
		fields["secret"] = encryptSecretIfPossible(item.Secret)
	} else if record.Id == "" {
		fields["secret"] = ""
	}

	for key, value := range fields {
		setIfFieldExists(record, collection, key, value)
	}
	return app.Save(record)
}

func upsertWalletStoreItem(ctx context.Context, store controlplane.WalletStore, tenantID string, req SyncRequest, item WalletItem) error {
	existing, err := findExistingWalletStoreItem(ctx, store, tenantID, req, item)
	if err != nil {
		return err
	}
	itemID := walletStoreItemID(tenantID, req, item)
	if existing != nil {
		itemID = existing.ID
	}
	_, err = store.UpsertWalletItem(ctx, controlplane.WalletItem{
		ID:          itemID,
		TenantID:    tenantID,
		StackID:     req.StackID,
		ItemType:    firstNonEmpty(item.Kind, "other"),
		Provider:    item.SourceType,
		ExternalRef: item.SourceRef,
		Metadata:    walletStoreMetadata(req, item),
	})
	return err
}

func findExistingWalletItem(app App, collection *core.Collection, req SyncRequest, item WalletItem) (*core.Record, error) {
	filter := "owner_id = {:ownerID} && stack_id = {:stackID} && service_id = {:serviceID}"
	params := dbx.Params{
		"ownerID":   req.OwnerID,
		"stackID":   req.StackID,
		"serviceID": item.ServiceID,
	}
	if collection.Fields.GetByName("source_ref") != nil && strings.TrimSpace(item.SourceRef) != "" {
		filter += " && source_ref = {:sourceRef}"
		params["sourceRef"] = item.SourceRef
	}
	records, err := app.FindRecordsByFilter("wallet", filter, "", 1, 0, params)
	if err != nil {
		return nil, nil
	}
	if len(records) == 0 {
		return nil, nil
	}
	return records[0], nil
}

func findExistingWalletStoreItem(ctx context.Context, store controlplane.WalletStore, tenantID string, req SyncRequest, item WalletItem) (*controlplane.WalletItem, error) {
	items, err := store.ListWalletItems(ctx, tenantID, req.StackID)
	if err != nil {
		return nil, err
	}
	for i := range items {
		metadata := items[i].Metadata
		if firstNonEmpty(walletStoreString(metadata["owner_id"]), req.OwnerID) != req.OwnerID {
			continue
		}
		if walletStoreString(metadata["service_id"]) != item.ServiceID {
			continue
		}
		if item.SourceRef != "" && walletStoreString(metadata["source_ref"]) != item.SourceRef {
			continue
		}
		return &items[i], nil
	}
	return nil, nil
}

func walletStoreMetadata(req SyncRequest, item WalletItem) map[string]any {
	fields := map[string]any{
		"owner_id":       req.OwnerID,
		"stack_id":       req.StackID,
		"service_id":     item.ServiceID,
		"source_ref":     item.SourceRef,
		"name":           item.Name,
		"kind":           firstNonEmpty(item.Kind, "other"),
		"username":       item.Username,
		"url":            item.URL,
		"notes":          item.Notes,
		"item_class":     item.ItemClass,
		"source_type":    item.SourceType,
		"access_mode":    item.AccessMode,
		"revealable":     item.Revealable,
		"auto_generated": item.AutoGenerated,
	}
	if item.Secret != "" {
		fields["secret"] = encryptSecretIfPossible(item.Secret)
	} else {
		fields["secret"] = ""
	}
	return fields
}

func walletStoreItemID(tenantID string, req SyncRequest, item WalletItem) string {
	sum := sha256.Sum256([]byte(strings.Join([]string{
		tenantID,
		req.OwnerID,
		req.StackID,
		item.ServiceID,
		item.SourceRef,
	}, "\x00")))
	return "wallet_" + hex.EncodeToString(sum[:])[:24]
}

func firstNestedMap(root map[string]interface{}, paths ...[]string) map[string]interface{} {
	for _, path := range paths {
		current := root
		ok := true
		for _, segment := range path {
			next, found := mapFromAny(current[segment])
			if !found {
				ok = false
				break
			}
			current = next
		}
		if ok {
			return current
		}
	}
	return nil
}

func recoverySecretRef(recovery map[string]interface{}) string {
	return firstOutputString(
		recovery,
		"recovery_bundle_ref",
		"bundle_ref",
		"passphrase_hash_ref",
		"machine_secret_ref",
		"secret_ref",
		"secret",
		"passphrase_hash",
	)
}

func firstOutputString(values map[string]interface{}, keys ...string) string {
	for _, key := range keys {
		if values == nil {
			if strings.TrimSpace(key) != "" {
				return key
			}
			continue
		}
		if value := stringFromAny(values[key]); value != "" {
			return value
		}
		if strings.Contains(key, ":") || strings.Contains(key, " ") {
			return key
		}
	}
	return ""
}

func mapFromAny(value interface{}) (map[string]interface{}, bool) {
	switch v := value.(type) {
	case map[string]interface{}:
		return v, true
	default:
		return nil, false
	}
}

func stringFromAny(value interface{}) string {
	switch v := value.(type) {
	case string:
		return strings.TrimSpace(v)
	default:
		return ""
	}
}

func walletStoreString(value any) string {
	switch v := value.(type) {
	case string:
		return strings.TrimSpace(v)
	case fmt.Stringer:
		return strings.TrimSpace(v.String())
	default:
		return ""
	}
}

func displayStackName(req SyncRequest) string {
	return firstNonEmpty(req.StackName, req.StackID, "stack")
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	return ""
}

func encryptSecretIfPossible(secret string) string {
	secret = strings.TrimSpace(secret)
	if secret == "" {
		return ""
	}
	encrypted, err := tsauth.EncryptIfNeeded(tsauth.GetEncryptor(), secret)
	if err != nil {
		return secret
	}
	return encrypted
}

func setIfFieldExists(record *core.Record, collection *core.Collection, field string, value any) {
	if record == nil || collection == nil {
		return
	}
	if collection.Fields.GetByName(field) == nil {
		return
	}
	record.Set(field, value)
}
