// kombify Techstack Agent Protocol
// gRPC with mTLS for secure, bidirectional agent communication

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Register_FullMethodName            = "/techstack.agent.v1.AgentService/Register"
	AgentService_Heartbeat_FullMethodName           = "/techstack.agent.v1.AgentService/Heartbeat"
	AgentService_CommandStream_FullMethodName       = "/techstack.agent.v1.AgentService/CommandStream"
	AgentService_ReportStatus_FullMethodName        = "/techstack.agent.v1.AgentService/ReportStatus"
	AgentService_RunPreChecks_FullMethodName        = "/techstack.agent.v1.AgentService/RunPreChecks"
	AgentService_PushMetrics_FullMethodName         = "/techstack.agent.v1.AgentService/PushMetrics"
	AgentService_GetSystemInfo_FullMethodName       = "/techstack.agent.v1.AgentService/GetSystemInfo"
	AgentService_ReportHealEvent_FullMethodName     = "/techstack.agent.v1.AgentService/ReportHealEvent"
	AgentService_ReportDetection_FullMethodName     = "/techstack.agent.v1.AgentService/ReportDetection"
	AgentService_StreamLogs_FullMethodName          = "/techstack.agent.v1.AgentService/StreamLogs"
	AgentService_GetUpdateCandidates_FullMethodName = "/techstack.agent.v1.AgentService/GetUpdateCandidates"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService handles communication between Core and Agents
type AgentServiceClient interface {
	// Register authenticates and registers an agent with the core
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat maintains connection and reports agent status
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// CommandStream is a bidirectional stream for real-time commands
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, CoreMessage], error)
	// ReportStatus sends detailed status updates from agent to core
	ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusAck, error)
	// RunPreChecks executes pre-deployment checks on the agent (H6a)
	RunPreChecks(ctx context.Context, in *PreCheckRequest, opts ...grpc.CallOption) (*PreCheckResponse, error)
	// PushMetrics receives batched metric samples from agents (Monitoring 2.0)
	PushMetrics(ctx context.Context, in *MetricsBatch, opts ...grpc.CallOption) (*PushAck, error)
	// GetSystemInfo returns a full snapshot of the server's state.
	GetSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error)
	// ReportHealEvent reports an autonomous self-heal action taken by the watchdog.
	ReportHealEvent(ctx context.Context, in *HealEventReport, opts ...grpc.CallOption) (*HealEventAck, error)
	// ReportDetection reports a detected issue that requires user attention.
	ReportDetection(ctx context.Context, in *DetectionReport, opts ...grpc.CallOption) (*DetectionAck, error)
	// StreamLogs opens a server-side stream of log entries for a given service.
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// GetUpdateCandidates returns available OS/package/container updates.
	GetUpdateCandidates(ctx context.Context, in *UpdateCandidatesRequest, opts ...grpc.CallOption) (*UpdateCandidatesResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, CoreMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, CoreMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_CommandStreamClient = grpc.BidiStreamingClient[AgentMessage, CoreMessage]

func (c *agentServiceClient) ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusAck)
	err := c.cc.Invoke(ctx, AgentService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RunPreChecks(ctx context.Context, in *PreCheckRequest, opts ...grpc.CallOption) (*PreCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreCheckResponse)
	err := c.cc.Invoke(ctx, AgentService_RunPreChecks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PushMetrics(ctx context.Context, in *MetricsBatch, opts ...grpc.CallOption) (*PushAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushAck)
	err := c.cc.Invoke(ctx, AgentService_PushMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemInfoResponse)
	err := c.cc.Invoke(ctx, AgentService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportHealEvent(ctx context.Context, in *HealEventReport, opts ...grpc.CallOption) (*HealEventAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealEventAck)
	err := c.cc.Invoke(ctx, AgentService_ReportHealEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportDetection(ctx context.Context, in *DetectionReport, opts ...grpc.CallOption) (*DetectionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectionAck)
	err := c.cc.Invoke(ctx, AgentService_ReportDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *agentServiceClient) GetUpdateCandidates(ctx context.Context, in *UpdateCandidatesRequest, opts ...grpc.CallOption) (*UpdateCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCandidatesResponse)
	err := c.cc.Invoke(ctx, AgentService_GetUpdateCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService handles communication between Core and Agents
type AgentServiceServer interface {
	// Register authenticates and registers an agent with the core
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat maintains connection and reports agent status
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// CommandStream is a bidirectional stream for real-time commands
	CommandStream(grpc.BidiStreamingServer[AgentMessage, CoreMessage]) error
	// ReportStatus sends detailed status updates from agent to core
	ReportStatus(context.Context, *StatusReport) (*StatusAck, error)
	// RunPreChecks executes pre-deployment checks on the agent (H6a)
	RunPreChecks(context.Context, *PreCheckRequest) (*PreCheckResponse, error)
	// PushMetrics receives batched metric samples from agents (Monitoring 2.0)
	PushMetrics(context.Context, *MetricsBatch) (*PushAck, error)
	// GetSystemInfo returns a full snapshot of the server's state.
	GetSystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error)
	// ReportHealEvent reports an autonomous self-heal action taken by the watchdog.
	ReportHealEvent(context.Context, *HealEventReport) (*HealEventAck, error)
	// ReportDetection reports a detected issue that requires user attention.
	ReportDetection(context.Context, *DetectionReport) (*DetectionAck, error)
	// StreamLogs opens a server-side stream of log entries for a given service.
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	// GetUpdateCandidates returns available OS/package/container updates.
	GetUpdateCandidates(context.Context, *UpdateCandidatesRequest) (*UpdateCandidatesResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) CommandStream(grpc.BidiStreamingServer[AgentMessage, CoreMessage]) error {
	return status.Error(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedAgentServiceServer) ReportStatus(context.Context, *StatusReport) (*StatusAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedAgentServiceServer) RunPreChecks(context.Context, *PreCheckRequest) (*PreCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunPreChecks not implemented")
}
func (UnimplementedAgentServiceServer) PushMetrics(context.Context, *MetricsBatch) (*PushAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PushMetrics not implemented")
}
func (UnimplementedAgentServiceServer) GetSystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedAgentServiceServer) ReportHealEvent(context.Context, *HealEventReport) (*HealEventAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHealEvent not implemented")
}
func (UnimplementedAgentServiceServer) ReportDetection(context.Context, *DetectionReport) (*DetectionAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDetection not implemented")
}
func (UnimplementedAgentServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedAgentServiceServer) GetUpdateCandidates(context.Context, *UpdateCandidatesRequest) (*UpdateCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUpdateCandidates not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).CommandStream(&grpc.GenericServerStream[AgentMessage, CoreMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_CommandStreamServer = grpc.BidiStreamingServer[AgentMessage, CoreMessage]

func _AgentService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportStatus(ctx, req.(*StatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RunPreChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RunPreChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RunPreChecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RunPreChecks(ctx, req.(*PreCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PushMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PushMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PushMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PushMetrics(ctx, req.(*MetricsBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSystemInfo(ctx, req.(*SystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportHealEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealEventReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportHealEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportHealEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportHealEvent(ctx, req.(*HealEventReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectionReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportDetection(ctx, req.(*DetectionReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _AgentService_GetUpdateCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetUpdateCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetUpdateCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetUpdateCandidates(ctx, req.(*UpdateCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "techstack.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _AgentService_ReportStatus_Handler,
		},
		{
			MethodName: "RunPreChecks",
			Handler:    _AgentService_RunPreChecks_Handler,
		},
		{
			MethodName: "PushMetrics",
			Handler:    _AgentService_PushMetrics_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _AgentService_GetSystemInfo_Handler,
		},
		{
			MethodName: "ReportHealEvent",
			Handler:    _AgentService_ReportHealEvent_Handler,
		},
		{
			MethodName: "ReportDetection",
			Handler:    _AgentService_ReportDetection_Handler,
		},
		{
			MethodName: "GetUpdateCandidates",
			Handler:    _AgentService_GetUpdateCandidates_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _AgentService_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _AgentService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
